name: Merge from main to localstorage
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch-localstorage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> localstorage
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: localstorage
          github_token: ${{ secrets.GITHUB_TOKEN }}

#  sync-branch-edge:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#
#      - name: Merge chrome-extension -> edge-extension
#        uses: devmasx/merge-branch@v1.3.1
#        with:
#          type: now
#          from_branch: chrome-extension
#          target_branch: edge-extension
#          github_token: ${{ secrets.GITHUB_TOKEN }}

#  sync-branch-opera:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#
#      - name: Merge chrome-extension -> opera-extension
#        uses: devmasx/merge-branch@v1.3.1
#        with:
#          type: now
#          from_branch: chrome-extension
#          target_branch: opera-extension
#          github_token: ${{ secrets.GITHUB_TOKEN }}
