name: Merge from main to localstorage
on:
  push:
    branches:
      - 'main'
jobs:
  sync-branch-main:
    runs-on: ubuntu-latest
    #    // https://github.com/devmasx/merge-branch/issues/34
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> localstorage
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: localstorage
          github_token: ${{ secrets.GITHUB_TOKEN }}
